[package]
name = "polkadot-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20",  features = ["derive"]  }
pty = "0.2"
lazy_static = "1.4"
mockall = "0.11"

[[bin]]
name = "dot"
path = "src/main.rs"

[dev-dependencies]
mockall = "0.11"