name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: |
        rustup component add clippy
        rustup component add rustfmt
        cargo install cargo-tarpaulin

    - name: Run tests with coverage
      run: |
        cargo tarpaulin --exclude-files src/main.rs
        cargo tarpaulin --ignore-tests --out Xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cobertura.xml
        flags: unittests
        fail_ci_if_error: true
